### ISSUE TITLE
Deprecations Issues

### ISSUE THREAD

**Issue by davidlapham** [jamrader/XTUltrasonicFingerprints#1]
I could be doing something wrong but I'm getting 14 deprecation issues and the fingerprints arn't triggering anything in the app. Am I missing something?

**Comment by jamrader** [comment]
Hey David, 

Are you talking about Android or iOS? I just updated the AAR with a new target version, which might help the issue on Android. There are some unsuppressed deprecation issues to accommodate earlier versions of Android, with things like UI colors. But if you're just running the demo app it should be basically plug-and-play.

**Comment by davidlapham** [comment]
My fault. IOS. I wasn’t sure if it was a volume thing? I had my volume cranked.  

Also, would love to see a basic tutorial on using this in a stand alone app.

**Comment by jamrader** [comment]
OK, great. Just a heads up -- in my experience louder volume doesn't equal better performance. Also, try to use only uncompressed WAV files. For example, even the videos uploaded on Vimeo undergo a compression algorithm that negatively effects performance. 

I'll also try to create a more in-depth tutorial on the integration process. Basically, a lot of the stuff in the demo app is UI fluff. The only really vital method is `didHearTriggerWithTitle: andAmplitude:`

**Comment by davidlapham** [comment]
Ok great!  Where do I find the wav files?

**Comment by jamrader** [comment]
My bad, I didn't make that clear in the readme. I added some starter triggers to the project now. If you need more triggers than that provided by the starter pack, just email info@qraider.com and we can set you up with some additional triggers.
