### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [jamrader/XTUltrasonicFingerprints#2]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
BTW this technology is amazing 👍

**Comment by jamrader** [comment]
Really glad you like it, I'd definitely open to adjusting the `README` to make it more accessible. Did you have any trouble with the iOS/Android integration steps in particular? I know right now I'm relying on people to integrate the project manually, that needs to change.

**Comment by jamesonrader** [comment]
@lfarah the README as been updated significantly and now provides much better step-by-step instructions as well as documentation regarding the engine callback structure, so I will mark this issue as closed.
