### ISSUE TITLE
Speaker availability

### ISSUE THREAD

**Issue by EXJUSTICE** [jamrader/XTUltrasonicFingerprints#5]
Hey man,

Messaged you before on reddit.
I wanted to ask if the SDK allows only for the receiving of the waveforms, not generation correct?
Could you use the phone speaker to generate something through the SDK?

Thanks

**Comment by jamesonrader** [comment]
Hi @EXJUSTICE this is a feature that does exist, actually. However, it is not yet production-ready/merged into master. That being the case, it should be by June 1, 2019 at the latest.

**Comment by jamesonrader** [comment]
@EXJUSTICE FYI, waveform generation is included in the latest release.
